---
abstract: 'Easy, versatile, portable file handling'
author:
  - 'Tommy Butler'
build_requires:
  File::Temp: 0
  Module::Build: 0.3601
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Util
requires:
  AutoLoader: 0
  Config: 0
  Exception::Handler: 1.00_0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  Fcntl: 0
  File::Temp: 0
  Module::Build: 0
  Test: 0
  constant: 0
  perl: 5.006
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=File%3A%3AUtil
  homepage: https://github.com/tommybutler/file-util/wiki
  repository: git://github.com/tommybutler/file-util.git
version: 3.36
