use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.004001
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
AND'ed
ascii
bitmask
BrowserUk
BLOCKEX
CIFS
conf
dat
dbitmask
ebcdic
EBCDIC
EPOC
failsafe
FIFOs
Github
html
inodes
listrefs
NFS
oct
onfail
SIGNES
SMB
Solaris
SOLARIS
subpattern
subref
subrefs
syntaxes
trunc
txt
unicode
VMS
vtab
benchmarking
merchantability
lexically
Tommy
Butler
lib
File
Util
Exception
Standard
Manual
Examples
Cookbook
Definitions
Diagnostic
Interface
Classic
Modern
